[package]
name = "sgfx-backend-scarlet-virgl-plugin"
version = "1.0.0"
edition = "2024"
license = "MIT"

[lib]
name = "sgfx_scarlet_virgl"
crate-type = ["cdylib"]

[target.'cfg(any(target_os = "scarlet", all(target_os = "linux", target_arch = "aarch64")))'.dependencies]
sgfx-backend-abi = { path = "../sgfx-backend-abi" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "040dbb5cf42b75489504e1765183d37f6131f54c", features = ["backend-abi"] }
sgfx-backend-scarlet-virgl = { path = "../sgfx-backend-scarlet-virgl", features = ["backend-abi"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("scarlet"))'] }
