[workspace]
resolver = "2"
members = [
    "crates/sgfx",
    "crates/sgfx-core",
    "crates/sgfx-codegen-virgl",
    "crates/sgfx-backend-wgpu",
    "crates/sgfx-backend-scarlet-virgl",
    "crates/vulkan-sgfx",
]
default-members = [
    "crates/sgfx",
    "crates/sgfx-core",
    "crates/sgfx-codegen-virgl",
    "crates/sgfx-backend-wgpu",
    "crates/vulkan-sgfx",
]
