[package]
name = "sgfx-backend-scarlet-virgl"
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/sgfx"

[features]
default = ["std"]
std = ["dep:scarlet-os", "gpu-raw/std", "programmable"]
scarlet-std = ["dep:scarlet-std", "gpu-raw/scarlet-std"]
programmable = ["sgfx-codegen-virgl/programmable"]

[dependencies]
scarlet-os = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4ea47edf7e37f50f3c286e2fe51c784f6d282cfe", default-features = false, features = ["std"], optional = true }
scarlet-std = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4ea47edf7e37f50f3c286e2fe51c784f6d282cfe", optional = true }
gpu-raw = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4ea47edf7e37f50f3c286e2fe51c784f6d282cfe", default-features = false }
sgfx-codegen-virgl = { path = "../sgfx-codegen-virgl" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "5ea41a0dfd6992bb1c0fce06c8e65425dc978140", default-features = false }

[lib]
name = "sgfx_backend_scarlet_virgl"
path = "src/lib.rs"
