[package]
name = "sgfx-backend-wgpu"
version = "0.16.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
raw-window-handle = "0.6"
sgfx-core = { path = "../sgfx", default-features = false }
wgpu = "24"

[lib]
name = "sgfx_backend_wgpu"
path = "src/lib.rs"
