[package]
name = "sgfx-backend-wgpu"
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/sgfx"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
raw-window-handle = "0.6"
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "0b4cf0984d9b17bd0646612428c44bf1505393a8", default-features = false }
wgpu = { version = "24", features = ["spirv"] }

[lib]
name = "sgfx_backend_wgpu"
path = "src/lib.rs"

[dev-dependencies]
naga = { version = "24", features = ["wgsl-in", "spv-out"] }
