[package]
name = "sgfx-codegen-virgl"
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/sgfx"

[dependencies]
naga = { version = "24", optional = true, features = ["wgsl-in", "spv-in"] }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "0b4cf0984d9b17bd0646612428c44bf1505393a8", default-features = false }

[features]
default = []
programmable = ["dep:naga"]

[dev-dependencies]
naga = { version = "24", features = ["wgsl-in", "spv-out"] }

[lib]
name = "sgfx_codegen_virgl"
path = "src/lib.rs"
