[package]
name = "sgfx-core"
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/sgfx"

[features]
default = []
std = []
backend-abi = ["dep:sgfx-backend-abi"]

[dependencies]
sgfx-backend-abi = { git = "https://github.com/petitstrawberry/sgfx", rev = "040dbb5cf42b75489504e1765183d37f6131f54c", optional = true }

[lib]
name = "sgfx_core"
path = "src/lib.rs"
